import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manually creating a sidebar
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: 'Getting Started',
    },

    {
      type: 'doc',
      id: 'cli',
      label: 'CLI',
    },

    {
      type: 'doc',
      id: 'import-existing-project',
      label: 'Importing an existing project',
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'config/configuration',
        'config/hooks',
        {
          type: 'category',
          label: 'Makers',
          items: [
            'config/makers/README',
            'config/makers/dmg',
            'config/makers/deb',
            'config/makers/rpm',
            'config/makers/snapcraft',
            'config/makers/squirrel.windows',
            'config/makers/zip',
            'config/makers/wix-msi',
            'config/makers/appx',
            'config/makers/flatpak',
            'config/makers/pkg',
          ],
        },
        {
          type: 'category',
          label: 'Publishers',
          items: [
            'config/publishers/README',
            'config/publishers/bitbucket',
            'config/publishers/electron-release-server',
            'config/publishers/github',
            'config/publishers/nucleus',
            'config/publishers/s3',
            'config/publishers/snapcraft',
            'config/publishers/gcs',
          ],
        },
        {
          type: 'category',
          label: 'Plugins',
          items: [
            'config/plugins/README',
            'config/plugins/fuses',
            'config/plugins/local-electron',
            'config/plugins/vite',
            'config/plugins/webpack',
            'config/plugins/auto-unpack-natives',
            'config/plugins/electronegativity',
          ],
        },
        'config/typescript-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/framework-integration/README',
        'guides/framework-integration/react',
        'guides/framework-integration/vue-3',
        'guides/framework-integration/react-with-typescript',
        'guides/framework-integration/parcel',
        'guides/create-and-add-icons',
        'guides/code-signing/README',
        'guides/code-signing/code-signing-macos',
        'guides/code-signing/code-signing-windows',
        'guides/developing-with-wsl',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/auto-update',
        'advanced/debugging',
        {
          type: 'category',
          label: 'Extending Electron Forge',
          items: [
            'advanced/extending-electron-forge/README',
            'advanced/extending-electron-forge/writing-makers',
            'advanced/extending-electron-forge/writing-plugins',
            'advanced/extending-electron-forge/writing-publishers',
            'advanced/extending-electron-forge/writing-templates',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/why-electron-forge',
        'core-concepts/build-lifecycle',
      ],
    },
    {
      type: 'category',
      label: 'Built-in Templates',
      items: [
        'templates/typescript-+-webpack-template',
        'templates/vite-+-typescript',
        'templates/vite',
        'templates/webpack-template',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
    },
    {
      type: 'link',
      label: 'FAQ',
      href: '/docs/faq',
    },
    {
      type: 'link',
      label: 'Changelog',
      href: '/docs/changelog',
    },
  ],
};

export default sidebars;