name: Lint

on:
  push:
  pull_request:
    branches:
      - v6
      - v7
  workflow_dispatch:
    inputs:
      fetch-external-links:
        type: boolean
        description: Check if external links are broken

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # tag: v4.1.1
    - name: Setup Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65  # tag: v4.0.0
      with:
        node-version: lts/*
    - name: Create a Temporary package.json
      run: npm init --yes
    - name: Install @electron/lint-roller
      run: npm install --save-dev @electron/lint-roller
    - name: Run markdownlint
      run: npx electron-markdownlint "**/*.md"
    - name: Lint JS in Markdown with standard
      run: npx electron-lint-markdown-standard --ignore-path .markdownlintignore --semi "**/*.md"
    - name: Lint links
      run: npx electron-lint-markdown-links --ignore-path .markdownlintignore "**/*.md"
      if: ${{ always() }}
    - name: Check external links
      run: npx electron-lint-markdown-links --ignore-path .markdownlintignore --fetch-external-links "**/*.md"
      if: ${{ github.event.inputs.fetch-external-links }}
